# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from master import views

urlpatterns = patterns('',
        url(r'^$', views.index, name='index'),
        url(r'^index/$', views.index, name='index'),
        url(r'^login/$', views.masterlogin, name='login'),
        url(r'^work/$', views.work, name='work'),
        url(r'^logout/$', views.masterlogout, name='logout'),
        url(r'^changepass/$', views.changepass, name='changepass'),
        url(r'^syssetting/$', views.index, name='syssetting'),
        url(r'openorclose/$', views.OpenOrClose.as_view(), name='openorclose'),
        url(r'importstudents/$', views.importstudents, name='importstudents'),
        url(r'addstubyhand/$', views.addstubyhand, name='addstubyhand'),
        url(r'activeonestudent/(?P<stu_auth_num>\d+)/$', views.activeonestudent, name='avtiveonestudent'),
        url(r'forbidonestudent/(?P<stu_auth_num>\d+)/$', views.forbidonestudent, name='forbidonestudent'),
        url(r'forbidallstudent/$', views.forbidallstudent, name='forbidallstudent'),
        url(r'activeallstudent/$', views.activeallstudent, name='activeallstudent'),
        url(r'viewstuinfo/$', views.viewstuinfo, name='viewstuinfo'),
        url(r'editstuinfo/(?P<stu_auth_num>\d+)/$', views.EditStuInfo.as_view(), name='editstuinfo'),
        url(r'addclass/$', views.addclass, name='addclass'),
        url(r'showclasses/$', views.showclasses, name='showclasses'),
        url(r'showotherclasses/$', views.showotherclasses, name='showotherclasses'),
        url(r'editclass/(?P<class_id>\d+)/$', views.EditClass.as_view(), name='editclass'),
        url(r'commitstudentclass/(?P<classid>\d+)/(?P<stu_auth_num>\d+)/$', views.CommitStudentClass.as_view(), name='commitstudentclass'),
        url(r'stuclassreportupload/(?P<classid>\d+)/(?P<stu_auth_num>\d+)/$', views.StuclassreportUpload, name='stuclassreportupload'),
        url(r'addstudenttoclass/$', views.AddStudentToClassView.as_view(), name='addstudenttoclass'),
        url(r'addadmin/$', views.addadmin, name='addadmin'),
        url(r'forbidadmin/(?P<username>\w+)/$', views.forbidadmin, name='forbidadmin'),
        url(r'activeadmin/(?P<username>\w+)/$', views.activeadmin, name='activeadmin'),
        url(r'mastermanage/$', views.AdminListView.as_view(), name='mastermanage'),
        url(r'editadmin/(?P<username>\w+)/$', views.EditAdminView.as_view(), name='editadmin'),
        url(r'systimeset/$', views.SysTimeSet.as_view(), name='systimeset'),
        url(r'addexproom/$', views.AddExpRoom.as_view(), name='addexproom'),
        url(r'editexproom/(?P<classroomid>\d+)/$', views.EditExpRoom.as_view(), name='editexproom'),
        url(r'viewexproom/$', views.StuDoExpView.as_view(), name='viewexproom'),
        url(r'showotherexproom/$', views.showotherexproom, name='showotherexproom'),
        url(r'addstudenttoexproom/$', views.AddStudentToExpRoomView.as_view(), name='addstudenttoexproom'),
        url(r'studoexpcomment/([\d-]+)/$', views.StuDoExpComment.as_view(), name='studoexpcomment'),
        url(r'commitexp/(?P<stu_auth_num>\d+)/(?P<sel_time_id>\d+)/', views.CommitExpView.as_view(), name='commitexp'),
        url(r'addnews/$', views.AddNewsView.as_view(), name='addnews'),
        url(r'viewnews/$', views.NewsListView.as_view(), name='viewnewslist'),
        url(r'deletenews/(?P<newsid>\d+)/$', views.deletenews, name='deletenews'),
        url(r'category/([\d-]+)/$', views.CategoryNewsView.as_view(), name='categorynewsview'),
        url(r'newsdetail/([\d-]+)/$', views.NewsDetail.as_view(), name='newsdetail'),
        url(r'addcategory/$', views.addcategory, name='addcategory'),
        url(r'editcategory/(?P<id>\d+)/$', views.EditCategoryView.as_view(), name='editcategory'),
        url(r'editnews/(?P<newsid>\d+)/$', views.EditNews.as_view(), name='editnews'),
    )
